<?php

declare(strict_types=1);

namespace Sylius\MateExtension\Tool\Resource;

use Mcp\Capability\Attribute\McpTool;
use Sylius\MateExtension\Kernel\HostContainerProvider;
use Sylius\MateExtension\Output\Envelope;
use Sylius\Resource\Metadata\MetadataInterface;
use Sylius\Resource\Metadata\RegistryInterface;
use Sylius\Resource\Model\ResourceInterface;

#[McpTool(
    name: 'sylius_resource_inspect',
    description: 'Rich diagnostic for a registered Sylius Resource by alias: classes wired, custom-factory signature check (must accept string $className — Sylius default), interface auto-detection vs explicit, ResourceInterface conformance, container service ids generated by ResourceBundle.',
)]
final class InspectResource
{
    private const REGISTRY = 'sylius.resource_registry';

    public function __construct(
        private readonly HostContainerProvider $host,
    ) {
    }

    /**
     * @return array<string, mixed>
     */
    public function __invoke(string $alias): array
    {
        if ('' === trim($alias)) {
            return Envelope::error('invalid_alias', 'Argument "alias" must not be empty.');
        }

        $registry = $this->host->getContainer()->get(self::REGISTRY);
        if (!$registry instanceof RegistryInterface) {
            return Envelope::error('registry_unavailable', 'Service "sylius.resource_registry" is not available.');
        }

        try {
            $metadata = $registry->get($alias);
        } catch (\InvalidArgumentException) {
            return Envelope::empty(sprintf(
                'Resource alias "%s" not registered. Call sylius_domain_resource_template to scaffold it.',
                $alias,
            ));
        }

        if (!$metadata instanceof MetadataInterface) {
            return Envelope::error('invalid_metadata', sprintf('Registry returned a non-metadata entry for "%s".', $alias));
        }

        $classes = [];
        foreach (['model', 'interface', 'repository', 'factory', 'form', 'controller'] as $name) {
            if ($metadata->hasClass($name)) {
                $classes[$name] = $metadata->getClass($name);
            }
        }

        $warnings = [];

        $resourceInterfaceImplemented = isset($classes['model']) && is_a($classes['model'], ResourceInterface::class, true);
        if (!$resourceInterfaceImplemented) {
            $warnings[] = sprintf(
                'Model "%s" does not implement Sylius\\Resource\\Model\\ResourceInterface.',
                $classes['model'] ?? '(unset)',
            );
        }

        $interfaceMode = 'unknown';
        if (isset($classes['interface'])) {
            $interfaceMode = 'explicit';
        } elseif (isset($classes['model']) && interface_exists($classes['model'] . 'Interface')) {
            $interfaceMode = 'auto_detected';
        } else {
            $interfaceMode = 'missing';
            $warnings[] = 'No interface class configured and no <Model>Interface auto-detectable in the same namespace.';
        }

        $factoryStatus = $this->factoryStatus($classes['factory'] ?? null, $warnings);

        return Envelope::items(
            [[
                'alias' => $alias,
                'application' => $metadata->getApplicationName(),
                'name' => $metadata->getName(),
                'plural_name' => $metadata->getPluralName(),
                'driver' => $metadata->getDriver(),
                'classes' => $classes,
                'resource_interface_implemented' => $resourceInterfaceImplemented,
                'interface_mode' => $interfaceMode,
                'factory' => $factoryStatus,
                'service_ids' => [
                    'factory' => $metadata->getServiceId('factory'),
                    'manager' => $metadata->getServiceId('manager'),
                    'repository' => $metadata->getServiceId('repository'),
                    'controller' => $metadata->getServiceId('controller'),
                    'form' => $metadata->getServiceId('form'),
                ],
                'warnings' => $warnings,
            ]],
            null,
            [] === $warnings
                ? sprintf('Resource "%s" looks healthy.', $alias)
                : sprintf('Resource "%s" has %d warning(s).', $alias, \count($warnings)),
        );
    }

    /**
     * @param list<string> $warnings
     *
     * @return array<string, mixed>
     */
    private function factoryStatus(?string $factoryClass, array &$warnings): array
    {
        if (null === $factoryClass) {
            return ['mode' => 'default', 'class' => null, 'constructor_signature_ok' => true];
        }

        if (!class_exists($factoryClass)) {
            $warnings[] = sprintf('Configured factory class "%s" not autoloadable.', $factoryClass);

            return ['mode' => 'custom', 'class' => $factoryClass, 'constructor_signature_ok' => false];
        }

        $reflection = new \ReflectionClass($factoryClass);
        $constructor = $reflection->getConstructor();
        $signatureOk = false;
        if (null !== $constructor) {
            $params = $constructor->getParameters();
            if (1 === \count($params)) {
                $type = $params[0]->getType();
                $isString = $type instanceof \ReflectionNamedType && 'string' === $type->getName();
                $signatureOk = $isString && 'className' === $params[0]->getName();
            }
        }

        if (!$signatureOk) {
            $warnings[] = sprintf(
                'Custom factory "%s" must declare __construct(string $className) to plug into the Sylius ResourceBundle compiler pass. Wrap or decorate via a separate service id instead.',
                $factoryClass,
            );
        }

        return ['mode' => 'custom', 'class' => $factoryClass, 'constructor_signature_ok' => $signatureOk];
    }
}
